repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1000]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: mypy-src
        name: mypy (src)
        entry: mypy
        language: system
        pass_filenames: false
        args: [--strict, src]
      - id: mypy-tests
        name: mypy (tests)
        entry: mypy
        language: system
        pass_filenames: false
        args: [--strict, tests]
