name: Docs Build (strict)

"on":
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python] mkdocs-htmlproofer-plugin
          # Install project (optional if mkdocstrings imports need code)
          pip install -e .

      - name: Build docs (strict)
        run: |
          mkdocs build --strict
