# Reusable workflow for code quality checks
# Called by both CI and release workflows to ensure consistency
# Accepts Python version as input to support version matrix testing
name: Reusable Python Checks

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      test-command:
        required: true
        type: string

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      # Checkout code and set up Python environment
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: make install-dev

      - name: Lint code
        run: make lint

      - name: Run Tests
        env:
          # Set the Makefile variable based on the PR's draft status.
          # The 'true' on the end is needed because github.event.pull_request.draft is a boolean.
          TEST_LOG_LEVEL: ${{ github.event.pull_request.draft == 'true' && 'DEBUG' || 'WARNING' }}
        run: ${{ inputs.test-command }}
